# Site settings
title: oracledba.net

description: Website about Oracle DataBases, Weblogic servers and other Oracle technologies
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://oracledba.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
